name: C CI for GCC

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - name: make
      run: make
    - name: compiler-test
      run: make compiler-test
    - name: coverage-report
      run: make -C test/coverage-gcov/
