name: C CI for clang on Mac OS

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4.1.5
    - name: make using zsh instead of bash
      run: ./configure.sh && make CC=clang
