name: C CI for clang

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.5
    - name: install dependencies
      run: sudo apt-get install llvm
    - name: make
      run: make CC=clang
    - name: compiler-test
      run: make CC=clang compiler-test
    - name: coverage-report
      run: make CC=clang -C test/coverage-clang/
