name: C CI for clang

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: info
      run: clang --version
    - name: make
      run: make CC=clang
    - name: compiler-test
      run: make CC=clang compiler-test
