name: C CI for clang on Mac OS

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: patch to zsh
      run: ./configure.sh
    - name: make
      run: make CC=clang
