name: C CI for clang on Mac OS

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make CC=clang ACEUNIT:=$(pwd)/bin/aceunit.zsh ACEUNIT_FLAGS+="-s _"
    - name: coverage-report
      run: make CC=clang -C test/coverage-clang/
